// Generated by CoffeeScript 1.6.3
var link, markup;

link = function(x) {
  return "<a href='" + x + "'>" + x + "</a>";
};

markup = function(item) {
  return "<div class='line'>    <div class='title'>      " + item.html + "    </div>    <div class='links'>      " + (item.links.map(link).join('<br>')) + "    </div>    <div class='time'>      " + item.time + "    </div>  </div>";
};

$.getJSON('./analyse/unique-data.json', function(list) {
  return $('#entry').html(list.map(markup).join(''));
});

/*
//@ sourceMappingURL=arrange.map
*/
