// Generated by CoffeeScript 1.6.3
var collection;

collection = [];

chrome.extension.onMessage.addListener(function(message, sender, sendResponse) {
  collection.push.apply(collection, message.list);
  console.log(collection.length);
  return sendResponse({
    say: 'got it'
  });
});

/*
//@ sourceMappingURL=collector.map
*/
