// Generated by CoffeeScript 1.6.3
var delay, read, watch;

delay = function(t, f) {
  return setTimeout(f, t);
};

(watch = function() {
  var items;
  console.log('watching');
  window.scrollBy(0, 100000);
  items = $('div.WB_detail');
  return delay(1000, function() {
    if (items.length < 45) {
      return watch();
    } else {
      return read(items);
    }
  });
})();

read = function(items) {
  var data, it, item, list, _i, _len;
  list = [];
  for (_i = 0, _len = items.length; _i < _len; _i++) {
    item = items[_i];
    it = $(item);
    data = {
      html: it.find('.WB_text').html(),
      date: it.find('.WB_from [date]').attr('date'),
      time: it.find('.WB_from [date]').attr('title')
    };
    list.push(data);
  }
  return chrome.extension.sendMessage({
    list: list
  }, function() {
    var again, button;
    console.clear();
    button = $('.W_pages>a').get(1);
    if (button != null) {
      button.click();
    } else {
      $('.W_pages>a').click();
    }
    return (again = function() {
      return delay(1000, function() {
        var error;
        try {
          return watch();
        } catch (_error) {
          error = _error;
          return again();
        }
      });
    })();
  });
};

/*
//@ sourceMappingURL=walker.map
*/
